return {
	cache = {},
	wmgr_nlmt = 2,
	open_win_count = 0,
	window_timer = 300,
	indi_autocmd_id = 0,
	wmgr_time_lmt = 1000,
	indicator_timer = 1500,
	re_hlt_flg = false,
	window_notify = true,
	indicator_notify = true,
	win_hilght_acmd_id = 0,
	disp_ind_win_meta = {},
	win_mngr_valid_chrs = {
		["b"] = { sft = false },
		["c"] = { sft = false },
		["H"] = { sft = true },
		["h"] = { sft = false },
		["J"] = { sft = true },
		["j"] = { sft = false },
		["K"] = { sft = true },
		["k"] = { sft = false },
		["L"] = { sft = true },
		["l"] = { sft = false },
		["n"] = { sft = false },
		["o"] = { sft = false },
		["p"] = { sft = false },
		["q"] = { sft = false },
		["R"] = { sft = false },
		["r"] = { sft = false },
		["s"] = { sft = false },
		["T"] = { sft = false },
		["t"] = { sft = false },
		["v"] = { sft = false },
		["w"] = { sft = false },
		["x"] = { sft = false },
		[">"] = { sft = false },
		["<"] = { sft = false },
		["="] = { sft = false },
		["+"] = { sft = false },
		["-"] = { sft = false },
		["|"] = { sft = false },
		["_"] = { sft = false },
	},
}
